### ISSUE TITLE
Black integration doesn't work with some `pyproject.toml` configurations

### ISSUE THREAD

**Issue by Jackenmen** [timothycrosley/quickpython#4]
This is my `pyproject.toml`:
```toml
[tool.black]
target-version = ['py38']
```
and it sadly doesn't work with `quickpython`:
![image](https://user-images.githubusercontent.com/6032823/110215430-13672900-7eaa-11eb-9590-3b3d0d46a3fd.png)
